spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_2010_mybatis?characterEncoding=utf-8
      username: root
      password: gaofei12345
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.huanhuangf.gfadmin.entity